project_id = "qdjfzjqhnhrlkpqdtssp"

[functions.check-property-updates]
verify_jwt = false

[functions.get-violation-definition]
verify_jwt = false

[functions.hourly-violation-check]
verify_jwt = false

[functions.test-push-notification]
verify_jwt = false

[functions.aasa]
verify_jwt = false

[functions.apple-app-site-association]
verify_jwt = false
